import type { InsertEnquiriesLibraryItem } from "../shared/schema";

export const ENQUIRY_TEMPLATES: Record<string, number[]> = {};

export const SEED_ENQUIRIES: InsertEnquiriesLibraryItem[] = [
  {
    category: "Contract & Parties",
    subcategory: "Authority to sell",
    title: "Authority to act",
    enquiryText: "Please confirm whether there are any persons aged 17 or over who are in occupation of the property but are not named as registered proprietors, and if so, please confirm they will sign the contract as a party or provide vacant possession.",
    appliesTo: "purchase",
    tags: ["occupation", "contract"],
    whenToUse: "When title or TA6 indicates possible occupiers not on the title.",
    graceParagraph: "Cat B Part 2",
  },
  {
    category: "Contract & Parties",
    subcategory: "Authority to sell",
    title: "Power of Attorney",
    enquiryText: "We note the property is being sold under a Power of Attorney. Please supply a certified copy of the Power of Attorney and confirm it has not been revoked.",
    appliesTo: "purchase",
    tags: ["power-of-attorney", "title"],
    whenToUse: "When title register discloses a restriction referencing a Power of Attorney.",
    graceParagraph: "Cat B Part 2",
  },
  {
    category: "Contract & Parties",
    subcategory: "Capacity",
    title: "Personal representatives",
    enquiryText: "We note the sellers are acting as personal representatives. Please supply a copy of the Grant of Probate / Letters of Administration and confirm all necessary assents have been or will be completed.",
    appliesTo: "purchase",
    tags: ["probate", "personal-representatives"],
    whenToUse: "When title or instructions indicate sellers acting in representative capacity.",
    graceParagraph: "Cat B Part 2",
  },
  {
    category: "Contract & Parties",
    subcategory: "Capacity",
    title: "Company seller – authority",
    enquiryText: "Please confirm the seller company is not subject to any winding-up petition, administration order, or striking-off action, and that the signatory has authority to execute the transfer.",
    appliesTo: "purchase",
    tags: ["company", "authority"],
    whenToUse: "When the seller is a limited company.",
    graceParagraph: "Cat B Part 2",
  },
  {
    category: "Contract & Parties",
    subcategory: "Deposit",
    title: "Deposit held as agent or stakeholder",
    enquiryText: "Please confirm whether the deposit will be held as agent or stakeholder, and if as agent, please confirm the basis on which it will be released prior to completion.",
    appliesTo: "purchase",
    tags: ["deposit", "completion"],
    whenToUse: "When contract terms regarding deposit need clarification.",
    graceParagraph: "Cat B Part 6",
  },

  {
    category: "Title & Register",
    subcategory: "Registered title",
    title: "Missing title deeds – unregistered land",
    enquiryText: "Please supply an epitome of title demonstrating at least 15 years good root of title, or confirm arrangements for first registration and any title insurance proposed.",
    appliesTo: "purchase",
    tags: ["unregistered", "title-deeds"],
    whenToUse: "When dealing with unregistered land and title deeds are needed.",
    graceParagraph: "Cat B Part 2",
  },
  {
    category: "Title & Register",
    subcategory: "Entries",
    title: "Restriction on title – consent required",
    enquiryText: "We note a restriction on the title register requiring [specify consent/certificate]. Please confirm this will be complied with on or before completion and supply the relevant consent or certificate.",
    appliesTo: "purchase",
    tags: ["restriction", "consent"],
    whenToUse: "When there is a restriction on the register that requires action before transfer.",
    graceParagraph: "Cat B Part 2",
  },
  {
    category: "Title & Register",
    subcategory: "Entries",
    title: "Notice or caution on title",
    enquiryText: "We note a [notice/caution] entered on the register in favour of [name]. Please confirm the nature of this interest and whether it will be removed or overridden on completion.",
    appliesTo: "purchase",
    tags: ["notice", "caution", "title"],
    whenToUse: "When the register shows a notice/caution that may affect the buyer.",
    graceParagraph: "Cat B Part 2",
  },
  {
    category: "Title & Register",
    subcategory: "Entries",
    title: "Discrepancy in registered proprietor name",
    enquiryText: "We note a discrepancy between the name on the register and the seller's name as provided. Please clarify and confirm arrangements for any necessary application to HM Land Registry.",
    appliesTo: "purchase",
    tags: ["name-discrepancy", "title"],
    whenToUse: "When the seller's name does not exactly match the registered proprietor.",
    graceParagraph: "Cat B Part 2",
  },
  {
    category: "Title & Register",
    subcategory: "Charges",
    title: "Second charge – discharge arrangements",
    enquiryText: "We note a second charge registered in favour of [lender]. Please confirm this will be discharged on or before completion and that you hold or will obtain a redemption statement.",
    appliesTo: "purchase",
    tags: ["charge", "mortgage", "redemption"],
    whenToUse: "When there is more than one charge and the additional charge needs clarification.",
    graceParagraph: "Cat A Part 2 – but legitimate if not covered by TA13",
  },
  {
    category: "Title & Register",
    subcategory: "Leasehold",
    title: "Lease term remaining",
    enquiryText: "Please confirm the unexpired term of the lease and whether the seller or any predecessor has served or received any notice under the Leasehold Reform Act.",
    appliesTo: "purchase",
    tags: ["leasehold", "lease-extension"],
    whenToUse: "When purchasing a leasehold property, especially if the unexpired term may be short.",
    graceParagraph: "Cat B Part 2",
  },

  {
    category: "Boundaries & Rights",
    subcategory: "Boundaries",
    title: "Boundary dispute or alteration",
    enquiryText: "We note from [source, e.g., TA6 reply / title plan comparison] an indication that the physical boundaries may have been altered. Please provide details of any boundary agreement, dispute, or alteration and copies of any relevant correspondence.",
    appliesTo: "purchase",
    tags: ["boundary", "dispute"],
    whenToUse: "When TA6 or title plan inspection reveals a potential boundary issue. Do NOT raise generically.",
    graceParagraph: "Cat A Part 6 / Cat B Part 2 – only raise when triggered by evidence",
  },
  {
    category: "Boundaries & Rights",
    subcategory: "Rights",
    title: "Right of way – specific",
    enquiryText: "The title includes a right of way over [describe route]. Please confirm this right is currently exercisable without obstruction and whether any disputes have arisen regarding its use.",
    appliesTo: "purchase",
    tags: ["right-of-way", "easement", "access"],
    whenToUse: "When the title refers to a specific right of way that may be critical for access.",
    graceParagraph: "Cat B Part 2",
  },
  {
    category: "Boundaries & Rights",
    subcategory: "Rights",
    title: "Shared access or driveway",
    enquiryText: "The property benefits from / is subject to a shared [driveway/access]. Please confirm any maintenance contributions, current arrangements, and whether any dispute has arisen.",
    appliesTo: "purchase",
    tags: ["shared-access", "maintenance"],
    whenToUse: "When the title or plan shows shared access arrangements.",
    graceParagraph: "Cat B Part 2",
  },
  {
    category: "Boundaries & Rights",
    subcategory: "Rights",
    title: "Rights of light or air",
    enquiryText: "Are there any agreements, disputes or notices relating to rights of light or air affecting the property?",
    appliesTo: "purchase",
    tags: ["rights-of-light"],
    whenToUse: "When the property or its neighbours have been subject to development that may affect rights of light.",
    graceParagraph: "Cat B Part 6",
  },
  {
    category: "Boundaries & Rights",
    subcategory: "Party walls",
    title: "Party Wall Act notices",
    enquiryText: "Have any notices been served or received under the Party Wall etc. Act 1996 in relation to the property? If so, please supply copies of all notices, awards, and related correspondence.",
    appliesTo: "purchase",
    tags: ["party-wall", "notice"],
    whenToUse: "When TA6 or search results indicate potential party wall works, or the property is terraced/semi-detached and works have been carried out nearby.",
    graceParagraph: "Cat B Part 3",
  },

  {
    category: "Covenants & Restrictions",
    subcategory: "Restrictive covenants",
    title: "Breach of restrictive covenant – specific",
    enquiryText: "We note a restrictive covenant at entry [number] prohibiting [describe]. From [TA6/inspection/title], it appears this covenant may have been breached by [describe]. Please confirm whether any consent was obtained or indemnity insurance is in place.",
    appliesTo: "purchase",
    tags: ["covenant", "breach", "indemnity"],
    whenToUse: "When there is a specific, evidenced breach of a covenant visible from documents or TA6.",
    graceParagraph: "Cat B Part 2",
  },
  {
    category: "Covenants & Restrictions",
    subcategory: "Restrictive covenants",
    title: "Covenant – modification or discharge",
    enquiryText: "Has any application been made to the Upper Tribunal (Lands Chamber) to modify or discharge the restrictive covenant(s) noted on the title?",
    appliesTo: "purchase",
    tags: ["covenant", "modification"],
    whenToUse: "When the covenant is potentially obsolete and the buyer needs assurance.",
    graceParagraph: "Cat B Part 2",
  },
  {
    category: "Covenants & Restrictions",
    subcategory: "Positive covenants",
    title: "Positive covenant – estate maintenance",
    enquiryText: "Please supply details of any estate maintenance charge or contribution payable under positive covenants, including the current annual amount, the collecting entity, and any arrears.",
    appliesTo: "purchase",
    tags: ["positive-covenant", "maintenance-charge"],
    whenToUse: "When the title discloses positive covenants relating to estate or communal maintenance.",
    graceParagraph: "Cat B Part 2",
  },
  {
    category: "Covenants & Restrictions",
    subcategory: "Deed of covenant",
    title: "Deed of covenant required on transfer",
    enquiryText: "We note the title requires a deed of covenant to be entered into by the buyer. Please supply the form of deed of covenant and confirm the identity of the covenantee.",
    appliesTo: "purchase",
    tags: ["deed-of-covenant", "transfer"],
    whenToUse: "When the title register or transfer provisions require a deed of covenant from the buyer.",
    graceParagraph: "Cat B Part 2",
  },

  {
    category: "Planning & Building Regs",
    subcategory: "Planning permission",
    title: "Planning permission – conditions compliance",
    enquiryText: "We note planning permission [reference] was granted subject to conditions. Please confirm all pre-commencement and other conditions have been discharged and supply copies of the discharge notices.",
    appliesTo: "purchase",
    tags: ["planning", "conditions", "discharge"],
    whenToUse: "When the search reveals a planning permission with conditions that may not be evidenced as discharged.",
    graceParagraph: "Cat B Part 4",
  },
  {
    category: "Planning & Building Regs",
    subcategory: "Planning permission",
    title: "Planning – enforcement notice",
    enquiryText: "Our search reveals an enforcement notice [reference] has been served. Please supply full details, copies of the notice, and confirm the current position.",
    appliesTo: "purchase",
    tags: ["planning", "enforcement"],
    whenToUse: "When local authority search reveals an enforcement notice.",
    graceParagraph: "Cat B Part 4",
  },
  {
    category: "Planning & Building Regs",
    subcategory: "Building regulations",
    title: "Building regulations – completion certificate",
    enquiryText: "We note from the local authority search that building regulations approval was granted for [describe works] but no completion certificate is recorded. The works appear to be within the enforcement period. Please confirm whether a completion certificate was issued and supply a copy, or confirm what alternative evidence or insurance is available.",
    appliesTo: "purchase",
    tags: ["building-regs", "completion-certificate"],
    whenToUse: "When the search shows building regs approval but no completion certificate, and works are within the enforcement period.",
    graceParagraph: "Cat A Part 4 / Cat B Part 4 – only raise when within enforcement period",
  },
  {
    category: "Planning & Building Regs",
    subcategory: "Building regulations",
    title: "Building regulations – works without approval",
    enquiryText: "From [source], it appears that [describe works] may have been carried out without building regulations approval. The works appear to be within the enforcement period. Please confirm the position and whether regularisation or indemnity insurance is available.",
    appliesTo: "purchase",
    tags: ["building-regs", "no-approval"],
    whenToUse: "When evidence suggests works done without approval and within enforcement timeframes.",
    graceParagraph: "Cat B Part 4",
  },
  {
    category: "Planning & Building Regs",
    subcategory: "Listed building",
    title: "Listed building consent",
    enquiryText: "We note the property is listed [Grade]. Please confirm whether any works have been carried out since listing and, if so, whether listed building consent was obtained.",
    appliesTo: "purchase",
    tags: ["listed-building", "consent"],
    whenToUse: "When the property is a listed building and alterations appear to have been made.",
    graceParagraph: "Cat B Part 4",
  },
  {
    category: "Planning & Building Regs",
    subcategory: "Conservation area",
    title: "Conservation area – permitted development",
    enquiryText: "We note the property is within a conservation area. Please confirm whether any works have been carried out that may require planning permission due to restrictions on permitted development.",
    appliesTo: "purchase",
    tags: ["conservation-area", "permitted-development"],
    whenToUse: "When the search shows the property is in a conservation area and alterations are visible from evidence.",
    graceParagraph: "Cat B Part 4",
  },
  {
    category: "Planning & Building Regs",
    subcategory: "Certificates",
    title: "Electrical installation certificate",
    enquiryText: "Has an electrical installation condition report (EICR) or certificate been obtained for the current installation? If so, please supply a copy.",
    appliesTo: "purchase",
    tags: ["electrical", "certificate"],
    whenToUse: "When required by the buyer's lender. Do NOT raise generically; only when lender requirements specify.",
    graceParagraph: "Cat A Part 4 – generally not required unless lender-mandated",
  },
  {
    category: "Planning & Building Regs",
    subcategory: "Certificates",
    title: "Gas safety certificate",
    enquiryText: "If the property has a gas supply, please confirm whether a current gas safety certificate is available and supply a copy if required by the buyer's lender.",
    appliesTo: "purchase",
    tags: ["gas-safety", "certificate"],
    whenToUse: "Only when the buyer's lender specifically requires evidence of a gas safety certificate.",
    graceParagraph: "Cat A Part 4 – do not raise unless lender requires",
  },

  {
    category: "Searches",
    subcategory: "Local authority",
    title: "Local authority search – road adoption",
    enquiryText: "The local authority search reveals that the road fronting the property is not adopted. Please confirm the current position regarding adoption, any road charge liability, and whether a bond or agreement under Section 38 Highways Act 1980 exists.",
    appliesTo: "purchase",
    tags: ["highways", "unadopted-road", "search-follow-up"],
    whenToUse: "When the local authority search reveals the road is unadopted.",
    graceParagraph: "Cat B Part 5",
  },
  {
    category: "Searches",
    subcategory: "Local authority",
    title: "Local authority search – financial charge",
    enquiryText: "The local authority search reveals a financial charge registered against the property. Please supply details and confirm this will be discharged before or on completion.",
    appliesTo: "purchase",
    tags: ["local-authority", "financial-charge"],
    whenToUse: "When the local authority search discloses a charge on the property.",
    graceParagraph: "Cat B Part 5",
  },
  {
    category: "Searches",
    subcategory: "Environmental",
    title: "Environmental search – contamination flag",
    enquiryText: "The environmental search has flagged a potential contamination risk at or near the property. Please confirm whether the seller is aware of any contamination, remediation works, or environmental notices affecting the property.",
    appliesTo: "purchase",
    tags: ["environmental", "contamination"],
    whenToUse: "When the environmental search raises a contamination flag. Note: it is the buyer's responsibility to obtain appropriate reports, but the seller may have relevant knowledge.",
    graceParagraph: "Cat B Part 5",
  },
  {
    category: "Searches",
    subcategory: "Environmental",
    title: "Flood risk – insurance and history",
    enquiryText: "The environmental/flood search indicates a flood risk. Has the property ever flooded? Please confirm current buildings insurance is available and provide details of the insurer if applicable.",
    appliesTo: "purchase",
    tags: ["flood", "insurance"],
    whenToUse: "When flood search reveals elevated risk and buyer's lender requires flood insurance confirmation.",
    graceParagraph: "Cat B Part 5",
  },
  {
    category: "Searches",
    subcategory: "Drainage",
    title: "Drainage – connection to mains",
    enquiryText: "Please confirm whether the property is connected to mains drainage. If not, please provide details of the private drainage arrangements, any relevant consents (Environment Agency), and maintenance responsibilities.",
    appliesTo: "purchase",
    tags: ["drainage", "private-drainage"],
    whenToUse: "When drainage search or TA6 indicates the property is not connected to mains.",
    graceParagraph: "Cat B Part 5",
  },
  {
    category: "Searches",
    subcategory: "Drainage",
    title: "Public sewer within 3m",
    enquiryText: "The drainage search reveals a public sewer within 3 metres of the property. Please confirm whether any build-over agreement or consent has been obtained from the water authority.",
    appliesTo: "purchase",
    tags: ["sewer", "build-over"],
    whenToUse: "When drainage map shows a public sewer passing within or close to the property footprint.",
    graceParagraph: "Cat B Part 5",
  },
  {
    category: "Searches",
    subcategory: "Chancel repair",
    title: "Chancel repair liability",
    enquiryText: "The chancel repair search indicates potential liability. Please confirm whether chancel repair liability insurance is in place and supply a copy of the policy if so.",
    appliesTo: "purchase",
    tags: ["chancel-repair", "insurance"],
    whenToUse: "When the chancel repair search reveals potential liability.",
    graceParagraph: "Cat B Part 5",
  },
  {
    category: "Searches",
    subcategory: "Mining",
    title: "Mining search – subsidence claim",
    enquiryText: "The mining search reveals past mining activity. Has any subsidence claim been made in respect of the property? If so, please provide details and copies of any reports or settlement.",
    appliesTo: "purchase",
    tags: ["mining", "subsidence"],
    whenToUse: "When mining search reveals past mining and evidence of potential ground movement.",
    graceParagraph: "Cat B Part 5",
  },

  {
    category: "Leasehold",
    subcategory: "Service charge",
    title: "Service charge – accounts and demands",
    enquiryText: "Please supply copies of the last 3 years' service charge accounts and the current year's budget/estimate. Please also confirm whether there are any major works proposed or anticipated, and whether a Section 20 consultation has been or is being carried out.",
    appliesTo: "purchase",
    tags: ["leasehold", "service-charge", "section-20"],
    whenToUse: "On any leasehold purchase where service charges are payable.",
    graceParagraph: "Cat B Part 2",
  },
  {
    category: "Leasehold",
    subcategory: "Service charge",
    title: "Ground rent – current amount and review",
    enquiryText: "Please confirm the current ground rent, the review mechanism, and the date of the next review. If the ground rent exceeds or may exceed £250 per annum (or £1,000 in London), please confirm the position regarding assured tenancy risk.",
    appliesTo: "purchase",
    tags: ["leasehold", "ground-rent"],
    whenToUse: "On any leasehold purchase, especially where ground rent review clauses may cause issues for lenders.",
    graceParagraph: "Cat B Part 2",
  },
  {
    category: "Leasehold",
    subcategory: "Management",
    title: "Management company details",
    enquiryText: "Please supply the name and contact details of the current managing agent and confirm whether the management company is owned by the leaseholders (resident-managed) or by a third party.",
    appliesTo: "purchase",
    tags: ["leasehold", "management-company"],
    whenToUse: "On any leasehold purchase with a management company.",
    graceParagraph: "Cat B Part 2",
  },
  {
    category: "Leasehold",
    subcategory: "Management",
    title: "Leasehold – buildings insurance",
    enquiryText: "Please supply evidence of the current buildings insurance for the block, including confirmation that the interest of the buyer's lender can be noted on the policy.",
    appliesTo: "purchase",
    tags: ["leasehold", "insurance"],
    whenToUse: "On any leasehold purchase where the freeholder/management company arranges insurance.",
    graceParagraph: "Cat B Part 2",
  },
  {
    category: "Leasehold",
    subcategory: "Compliance",
    title: "Leasehold – licence for alterations",
    enquiryText: "We note from [source] that alterations appear to have been carried out to the property. Please confirm whether a licence for alterations was obtained from the landlord and supply a copy.",
    appliesTo: "purchase",
    tags: ["leasehold", "alterations", "licence"],
    whenToUse: "When evidence shows internal or external alterations to a leasehold property.",
    graceParagraph: "Cat B Part 2",
  },
  {
    category: "Leasehold",
    subcategory: "Compliance",
    title: "Leasehold – notice of transfer/charge",
    enquiryText: "Please confirm what notices are required to be served on the landlord/management company on assignment and any associated fee, and confirm you will serve such notices post-completion.",
    appliesTo: "purchase",
    tags: ["leasehold", "notice-of-transfer"],
    whenToUse: "On any leasehold purchase where the lease requires notice of assignment.",
    graceParagraph: "Cat B Part 2",
  },
  {
    category: "Leasehold",
    subcategory: "Lease extension",
    title: "Lease extension – informal or statutory",
    enquiryText: "Has the seller or any predecessor commenced any lease extension (whether informal or by statutory notice)? If so, please provide details and copies of all relevant notices and correspondence.",
    appliesTo: "purchase",
    tags: ["leasehold", "lease-extension"],
    whenToUse: "When the remaining term is short or a lease extension is in progress.",
    graceParagraph: "Cat B Part 2",
  },

  {
    category: "Completion Mechanics",
    subcategory: "Undertakings",
    title: "Undertaking to discharge – additional charges",
    enquiryText: "Please provide your professional undertaking to discharge all charges registered against the title on or before completion, in accordance with TA13.",
    appliesTo: "purchase",
    tags: ["undertaking", "charge", "TA13"],
    whenToUse: "Standard practice via TA13. Only raise separately if multiple charges create complexity.",
    graceParagraph: "Cat A Part 2 – covered by TA13",
  },
  {
    category: "Completion Mechanics",
    subcategory: "Keys",
    title: "Key release arrangements",
    enquiryText: "Please confirm arrangements for release of keys on completion, including the location from which keys will be available and the estate agent's contact details.",
    appliesTo: "purchase",
    tags: ["completion", "keys"],
    whenToUse: "As part of pre-completion checklist.",
    graceParagraph: "Cat B Part 6",
  },
  {
    category: "Completion Mechanics",
    subcategory: "Vacant possession",
    title: "Vacant possession confirmation",
    enquiryText: "Please confirm that vacant possession will be given on completion and that all occupiers will have vacated the property.",
    appliesTo: "purchase",
    tags: ["vacant-possession", "completion"],
    whenToUse: "When TA6 suggests occupiers or as standard pre-exchange confirmation.",
    graceParagraph: "Cat B Part 6",
  },
  {
    category: "Completion Mechanics",
    subcategory: "Apportionments",
    title: "Completion apportionments",
    enquiryText: "Please confirm the basis for any apportionments on completion (e.g., ground rent, service charge, council tax) and supply a completion statement in advance.",
    appliesTo: "purchase",
    tags: ["apportionments", "completion-statement"],
    whenToUse: "On leasehold purchases or where service charges/ground rent need apportionment.",
    graceParagraph: "Cat B Part 6",
  },
  {
    category: "Completion Mechanics",
    subcategory: "SDLT / Tax",
    title: "SDLT – linked transactions",
    enquiryText: "Are there any linked transactions within the meaning of section 108 Finance Act 2003 that may affect the SDLT payable on this purchase?",
    appliesTo: "purchase",
    tags: ["SDLT", "tax", "linked-transactions"],
    whenToUse: "When there are indications of connected transactions (e.g., buying from same seller, multiple purchases).",
    graceParagraph: "Cat B Part 6",
  },

  {
    category: "Contract & Parties",
    subcategory: "Contract terms",
    title: "Special conditions – review",
    enquiryText: "Please explain the reason for special condition [number] and confirm whether it is negotiable.",
    appliesTo: "purchase",
    tags: ["special-conditions", "contract"],
    whenToUse: "When the draft contract includes non-standard special conditions.",
    graceParagraph: "Cat B Part 1",
  },
  {
    category: "Contract & Parties",
    subcategory: "Contract terms",
    title: "Indemnity covenant – chain of indemnity",
    enquiryText: "We note a positive covenant requiring an indemnity covenant on transfer. Please confirm the chain of indemnity is complete and supply evidence.",
    appliesTo: "purchase",
    tags: ["indemnity", "covenant", "chain"],
    whenToUse: "When the title shows positive covenants requiring chain of indemnity.",
    graceParagraph: "Cat B Part 2",
  },

  {
    category: "Title & Register",
    subcategory: "Overriding interests",
    title: "Overriding interests",
    enquiryText: "Please confirm whether the seller is aware of any overriding interests affecting the property that are not apparent from the title register, including any rights of persons in actual occupation.",
    appliesTo: "purchase",
    tags: ["overriding-interests", "occupation"],
    whenToUse: "When the property may be subject to overriding interests (e.g., informal family arrangements).",
    graceParagraph: "Cat B Part 2",
  },
  {
    category: "Title & Register",
    subcategory: "Easements",
    title: "Easement – utility services",
    enquiryText: "The title refers to an easement for [utility services/drainage] over [land]. Please confirm the easement is exercisable and whether any issues have arisen with the servient owner.",
    appliesTo: "purchase",
    tags: ["easement", "utilities", "services"],
    whenToUse: "When the title shows an easement for utility services that could be disputed.",
    graceParagraph: "Cat B Part 2",
  },

  {
    category: "Boundaries & Rights",
    subcategory: "Fly-tipping / access",
    title: "Ransom strip",
    enquiryText: "Is any access to the property dependent on crossing land not included in the title? If so, please confirm the legal basis for such access.",
    appliesTo: "purchase",
    tags: ["ransom-strip", "access"],
    whenToUse: "When the title plan shows a potential gap between the property and the adopted highway.",
    graceParagraph: "Cat B Part 2",
  },

  {
    category: "Planning & Building Regs",
    subcategory: "Extensions/alterations",
    title: "Extension – planning and building regs",
    enquiryText: "We note from [TA6/search/inspection] that an extension has been built. Please confirm whether planning permission and building regulations approval were obtained and supply copies of the approvals and completion certificate.",
    appliesTo: "purchase",
    tags: ["extension", "planning", "building-regs"],
    whenToUse: "When evidence shows an extension and documentation is needed (within enforcement period).",
    graceParagraph: "Cat B Part 4",
  },
  {
    category: "Planning & Building Regs",
    subcategory: "Extensions/alterations",
    title: "Loft conversion – approvals",
    enquiryText: "We note the property has a loft conversion. Please confirm whether planning permission and building regulations approval were obtained, supply the completion certificate, and confirm a Party Wall Award was obtained if applicable.",
    appliesTo: "purchase",
    tags: ["loft-conversion", "building-regs"],
    whenToUse: "When evidence shows a loft conversion within enforcement period.",
    graceParagraph: "Cat B Part 4",
  },
  {
    category: "Planning & Building Regs",
    subcategory: "Extensions/alterations",
    title: "Conservatory – planning/building regs",
    enquiryText: "We note a conservatory at the property. Please confirm whether planning permission was required and obtained, and whether building regulations approval was required (particularly if there is a permanent connection to the main building or internal door has been removed).",
    appliesTo: "purchase",
    tags: ["conservatory", "planning"],
    whenToUse: "When a conservatory is visible from TA6 or plans and may require approvals.",
    graceParagraph: "Cat B Part 4",
  },
  {
    category: "Planning & Building Regs",
    subcategory: "Change of use",
    title: "Change of use",
    enquiryText: "Has the use of the property (or any part of it) been changed? If so, please confirm whether planning permission was obtained for the change of use and supply a copy.",
    appliesTo: "purchase",
    tags: ["change-of-use", "planning"],
    whenToUse: "When there are indications the property has changed use (e.g., HMO, commercial to residential).",
    graceParagraph: "Cat B Part 4",
  },
  {
    category: "Planning & Building Regs",
    subcategory: "Tree preservation",
    title: "Tree Preservation Order",
    enquiryText: "The search reveals a Tree Preservation Order affecting the property. Please confirm the seller is aware of this and has not carried out any unauthorised work to the protected trees.",
    appliesTo: "purchase",
    tags: ["TPO", "tree-preservation"],
    whenToUse: "When the search reveals a TPO and works may have been done to trees. Note: the TPO itself is public info; only raise if works may have breached it.",
    graceParagraph: "Cat B Part 5",
  },

  {
    category: "Searches",
    subcategory: "Water",
    title: "Water supply – private",
    enquiryText: "Please confirm whether the property has a private water supply and, if so, provide details of testing, maintenance responsibilities, and any relevant Environment Agency or local authority consents.",
    appliesTo: "purchase",
    tags: ["water-supply", "private"],
    whenToUse: "When evidence suggests the property is not on mains water.",
    graceParagraph: "Cat B Part 5",
  },
  {
    category: "Searches",
    subcategory: "Commons",
    title: "Common land – registration",
    enquiryText: "The search reveals common land or town/village green near the property. Please confirm whether any part of the property is registered as common land and whether this affects the use or development of the property.",
    appliesTo: "purchase",
    tags: ["common-land", "village-green"],
    whenToUse: "When commons registration search reveals common land adjacent to or near the property.",
    graceParagraph: "Cat B Part 5",
  },

  {
    category: "Completion Mechanics",
    subcategory: "Post-completion",
    title: "SDLT – reliefs and exemptions",
    enquiryText: "Please confirm whether the seller has claimed any SDLT relief (e.g., multiple dwellings relief) on their purchase that may be subject to clawback and could affect the buyer.",
    appliesTo: "purchase",
    tags: ["SDLT", "relief", "clawback"],
    whenToUse: "When SDLT reliefs may have been claimed on a recent acquisition.",
    graceParagraph: "Cat B Part 6",
  },

  {
    category: "Contract & Parties",
    subcategory: "New build",
    title: "New build – NHBC / warranty",
    enquiryText: "Please confirm what new home warranty is in place (e.g., NHBC Buildmark, Premier Guarantee, LABC) and supply a copy of the cover note and policy.",
    appliesTo: "purchase",
    tags: ["new-build", "warranty", "NHBC"],
    whenToUse: "On new-build purchases where a structural warranty is expected.",
    graceParagraph: "Cat B Part 1",
  },
  {
    category: "Contract & Parties",
    subcategory: "New build",
    title: "New build – snagging",
    enquiryText: "Please confirm the arrangements for the buyer to inspect and report defects (snagging) prior to or after completion.",
    appliesTo: "purchase",
    tags: ["new-build", "snagging"],
    whenToUse: "On new-build purchases.",
    graceParagraph: "Cat B Part 1",
  },
  {
    category: "Contract & Parties",
    subcategory: "New build",
    title: "New build – roads and sewers adoption",
    enquiryText: "Please confirm the position regarding adoption of roads and sewers on the development under Section 38 (Highways Act) and Section 104 (Water Industry Act) agreements. Please supply copies of the agreements.",
    appliesTo: "purchase",
    tags: ["new-build", "adoption", "highways"],
    whenToUse: "On new-build purchases on an estate or development.",
    graceParagraph: "Cat B Part 5",
  },

  {
    category: "Covenants & Restrictions",
    subcategory: "Estate covenants",
    title: "Estate rent charge",
    enquiryText: "We note an estate rent charge is payable. Please supply details of the current amount, the collecting entity, any arrears, and the remedies available to the rent charge owner.",
    appliesTo: "purchase",
    tags: ["rent-charge", "estate"],
    whenToUse: "When the title discloses an estate rent charge. Important post-Avon Ground Rents v Williams.",
    graceParagraph: "Cat B Part 2",
  },

  {
    category: "Title & Register",
    subcategory: "Adverse possession",
    title: "Adverse possession",
    enquiryText: "Has any claim been made or is the seller aware of any claim for adverse possession affecting any part of the property or any adjoining land?",
    appliesTo: "purchase",
    tags: ["adverse-possession", "title"],
    whenToUse: "When there are boundary discrepancies or indications of third-party encroachment.",
    graceParagraph: "Cat B Part 2",
  },

  {
    category: "Searches",
    subcategory: "HS2 / Infrastructure",
    title: "HS2 / major infrastructure",
    enquiryText: "The search reveals the property may be affected by [HS2/proposed infrastructure]. Please confirm whether any notices have been received and whether the seller has made any blight claim.",
    appliesTo: "purchase",
    tags: ["HS2", "infrastructure", "blight"],
    whenToUse: "When searches reveal potential impact from major infrastructure projects.",
    graceParagraph: "Cat B Part 5",
  },

  {
    category: "Leasehold",
    subcategory: "Forfeiture",
    title: "Leasehold – breaches and forfeiture risk",
    enquiryText: "Are there any outstanding breaches of the lease of which the seller is aware, or any current or threatened forfeiture proceedings?",
    appliesTo: "purchase",
    tags: ["leasehold", "forfeiture", "breach"],
    whenToUse: "On any leasehold purchase, particularly where lender requires confirmation.",
    graceParagraph: "Cat B Part 2",
  },

  {
    category: "Boundaries & Rights",
    subcategory: "Wayleaves",
    title: "Wayleaves and easements for utilities",
    enquiryText: "Are there any wayleaves or informal arrangements permitting utility companies to maintain equipment on or across the property? If so, please provide details.",
    appliesTo: "purchase",
    tags: ["wayleave", "utilities"],
    whenToUse: "When there are visible utility installations (pylons, substations, pipes) on the property.",
    graceParagraph: "Cat B Part 2",
  },

  {
    category: "Contract & Parties",
    subcategory: "Sale",
    title: "Sale – replies to buyer enquiries",
    enquiryText: "Please review and respond to the enclosed enquiries. Replies should reference the enquiry number. Where information is not available, please state this expressly rather than replying 'not known'.",
    appliesTo: "sale",
    tags: ["sale", "replies"],
    whenToUse: "Template cover text when replying to buyer's enquiries on a sale matter.",
    graceParagraph: "General",
  },
  {
    category: "Contract & Parties",
    subcategory: "Sale",
    title: "Sale – property information accuracy",
    enquiryText: "Please ensure all replies to the property information forms (TA6, TA7, TA10) are complete and accurate. Incomplete or evasive replies may delay the transaction.",
    appliesTo: "sale",
    tags: ["sale", "TA6", "TA7", "TA10"],
    whenToUse: "When sending out the initial sale pack.",
    graceParagraph: "General",
  },
  {
    category: "Completion Mechanics",
    subcategory: "Bank details",
    title: "Bank details – secure method",
    enquiryText: "In accordance with the Law Society Protocol and CQS requirements, please provide bank details via TA13 or by telephone verification. Bank details should NOT be sent by email.",
    appliesTo: "both",
    tags: ["bank-details", "cybersecurity", "TA13"],
    whenToUse: "Standard pre-completion. Always verify bank details by phone.",
    graceParagraph: "Cat A Part 6",
  },
  {
    category: "Completion Mechanics",
    subcategory: "Completion",
    title: "Completion – Code for Completion by Post",
    enquiryText: "Please confirm you will complete in accordance with the Law Society's Code for Completion by Post (2019 edition) and that you are authorised to give the appropriate undertakings.",
    appliesTo: "purchase",
    tags: ["completion", "code-for-completion"],
    whenToUse: "Standard pre-exchange/completion enquiry.",
    graceParagraph: "Cat A Part 1 / TA13",
  },
  {
    category: "Planning & Building Regs",
    subcategory: "Windows/doors",
    title: "Replacement windows – FENSA/CERTASS",
    enquiryText: "We note from [TA6/inspection] that replacement windows/doors have been installed. Please confirm whether FENSA or CERTASS registration was obtained, or whether a local authority building control completion certificate was issued.",
    appliesTo: "purchase",
    tags: ["windows", "FENSA", "building-regs"],
    whenToUse: "When TA6 or inspection reveals replacement windows and no evidence of compliance. Only raise within enforcement period.",
    graceParagraph: "Cat A Part 4 – do not request duplicates if search confirms; Cat B if within enforcement",
  },
  {
    category: "Planning & Building Regs",
    subcategory: "Boiler/heating",
    title: "Boiler/heating installation – Gas Safe",
    enquiryText: "We note from [TA6/inspection] that a new boiler/heating system has been installed. Please confirm a Gas Safe certificate was obtained and whether building regulations notification was made.",
    appliesTo: "purchase",
    tags: ["boiler", "gas-safe", "building-regs"],
    whenToUse: "When evidence shows a boiler was replaced and compliance documentation is needed. Only raise within enforcement period.",
    graceParagraph: "Cat B Part 4",
  },
  {
    category: "Planning & Building Regs",
    subcategory: "Solar/renewable",
    title: "Solar panels – ownership and planning",
    enquiryText: "We note solar panels are installed at the property. Please confirm whether these are owned outright or subject to a lease/PPA arrangement, and whether any planning permission or building regulations approval was required and obtained.",
    appliesTo: "purchase",
    tags: ["solar-panels", "renewable", "lease"],
    whenToUse: "When the property has solar panels which may be leased or subject to agreements.",
    graceParagraph: "Cat B Part 4",
  },
  {
    category: "Covenants & Restrictions",
    subcategory: "Freehold estate",
    title: "Freehold management scheme",
    enquiryText: "We note a freehold management scheme applies to the property. Please supply details of the management company, current contributions, any arrears, and copies of the most recent accounts.",
    appliesTo: "purchase",
    tags: ["management-scheme", "freehold"],
    whenToUse: "When the title shows a freehold property subject to a management scheme or estate charge.",
    graceParagraph: "Cat B Part 2",
  },
  {
    category: "Searches",
    subcategory: "Land charges",
    title: "Land charges search – entries found",
    enquiryText: "Our land charges search has revealed entries against the property. Please supply full details and confirm these will be dealt with prior to completion.",
    appliesTo: "purchase",
    tags: ["land-charges", "search"],
    whenToUse: "When the land charges search reveals entries that require explanation.",
    graceParagraph: "Cat B Part 5",
  },
  {
    category: "Boundaries & Rights",
    subcategory: "Parking",
    title: "Parking rights – allocated space",
    enquiryText: "Please confirm the parking arrangements for the property, whether a specific space is allocated, and the legal basis for its use (demise, easement, or licence).",
    appliesTo: "purchase",
    tags: ["parking", "rights"],
    whenToUse: "When the property includes or claims to include a parking space not clearly shown on the title.",
    graceParagraph: "Cat B Part 2",
  },
  {
    category: "Leasehold",
    subcategory: "EWS1",
    title: "External wall system – EWS1 form",
    enquiryText: "If the building is over 11m or 4+ storeys, please confirm whether an EWS1 form has been obtained and provide a copy. Please also confirm whether any fire safety remediation works are planned or in progress.",
    appliesTo: "purchase",
    tags: ["EWS1", "cladding", "fire-safety"],
    whenToUse: "On leasehold flats in buildings over 11m, or where required by the buyer's lender.",
    graceParagraph: "Cat B – lender requirement",
  },
  {
    category: "Leasehold",
    subcategory: "Deed of variation",
    title: "Lease – deed of variation",
    enquiryText: "Has the lease been varied by any supplemental deed or agreement? If so, please supply copies of all variations.",
    appliesTo: "purchase",
    tags: ["leasehold", "deed-of-variation"],
    whenToUse: "When there are indications the lease terms have been amended.",
    graceParagraph: "Cat B Part 2",
  },
];

export const STANDARD_ENQUIRIES: InsertEnquiriesLibraryItem[] = [
  {
    category: "Contract & Parties",
    subcategory: "Standard – Authority",
    title: "Std – Authority to sell",
    enquiryText: "Please confirm the seller has legal capacity and authority to sell the property.",
    appliesTo: "purchase",
    tags: ["purchase", "authority", "standard"],
    whenToUse: "Standard initial enquiry on all purchase matters.",
    graceParagraph: "Cat C",
  },
  {
    category: "Contract & Parties",
    subcategory: "Standard – Authority",
    title: "Std – Power of attorney / PR evidence",
    enquiryText: "If the seller is acting as attorney/personal representative, please provide evidence of authority.",
    appliesTo: "purchase",
    tags: ["purchase", "power-of-attorney", "standard"],
    whenToUse: "Only raise if title or instructions indicate attorney/PR capacity.",
    graceParagraph: "Cat B",
  },
  {
    category: "Title & Register",
    subcategory: "Standard – Restrictions",
    title: "Std – Title restrictions compliance",
    enquiryText: "Please confirm how the restriction in the proprietorship register will be complied with and provide any required certificate/consent.",
    appliesTo: "purchase",
    tags: ["purchase", "title", "restrictions", "standard"],
    whenToUse: "Standard enquiry whenever title register shows a restriction.",
    graceParagraph: "Cat C",
  },
  {
    category: "Boundaries & Rights",
    subcategory: "Standard – Access",
    title: "Std – Rights of way / access sufficiency",
    enquiryText: "Please confirm the rights granted/reserved in the title are sufficient for access to and from the public highway.",
    appliesTo: "purchase",
    tags: ["purchase", "access", "rights", "standard"],
    whenToUse: "Standard initial enquiry on all purchase matters.",
    graceParagraph: "Cat C",
  },
  {
    category: "Title & Register",
    subcategory: "Standard – Services",
    title: "Std – Services easements",
    enquiryText: "Please confirm the property benefits from adequate rights for services (drainage, water, gas, electricity, telecoms) and identify any third-party land crossed.",
    appliesTo: "purchase",
    tags: ["purchase", "services", "easement", "standard"],
    whenToUse: "Standard initial enquiry on all purchase matters.",
    graceParagraph: "Cat C",
  },
  {
    category: "Title & Register",
    subcategory: "Standard – Overriding",
    title: "Std – Overriding interests disclosure",
    enquiryText: "Please confirm the property will be sold free from overriding interests except those disclosed.",
    appliesTo: "purchase",
    tags: ["purchase", "overriding-interests", "standard"],
    whenToUse: "Standard initial enquiry on all purchase matters.",
    graceParagraph: "Cat C",
  },
  {
    category: "Title & Register",
    subcategory: "Standard – Charges",
    title: "Std – Discharge of registered charges",
    enquiryText: "Please confirm all registered charges will be discharged on or before completion.",
    appliesTo: "purchase",
    tags: ["purchase", "charge", "mortgage", "standard"],
    whenToUse: "Standard initial enquiry on all purchase matters.",
    graceParagraph: "Cat C",
  },
  {
    category: "Title & Register",
    subcategory: "Standard – Charges",
    title: "Std – Other charges / secured interests",
    enquiryText: "Please confirm whether there are any other secured interests affecting the property that will require redemption on completion.",
    appliesTo: "purchase",
    tags: ["purchase", "charge", "standard"],
    whenToUse: "Raise if there are indications of informal charges or second charges.",
    graceParagraph: "Cat B",
  },
  {
    category: "Boundaries & Rights",
    subcategory: "Standard – Access",
    title: "Std – Adopted highway access",
    enquiryText: "Please confirm the property enjoys legal access from the public highway (or provide details of any private road arrangements).",
    appliesTo: "purchase",
    tags: ["purchase", "access", "highways", "standard"],
    whenToUse: "Raise if title/search indicates potential access issues.",
    graceParagraph: "Cat B",
  },
  {
    category: "Boundaries & Rights",
    subcategory: "Standard – Access",
    title: "Std – Third-party access documentation",
    enquiryText: "Where access is over third-party land, please confirm the legal basis for that access and that it is enforceable.",
    appliesTo: "purchase",
    tags: ["purchase", "access", "easement", "standard"],
    whenToUse: "Raise only when title or plan shows access over third-party land.",
    graceParagraph: "Cat B",
  },
  {
    category: "Covenants & Restrictions",
    subcategory: "Standard – Covenants",
    title: "Std – Specific covenant breach clarification",
    enquiryText: "Please confirm whether there has been any breach of the restrictive covenant dated [DATE] relating to [SPECIFIC COVENANT]. If consent was required, please provide evidence of consent/approval.",
    appliesTo: "purchase",
    tags: ["purchase", "covenant", "breach", "standard"],
    whenToUse: "Only raise if a specific covenant breach is identified from title or evidence.",
    graceParagraph: "Cat B",
  },
  {
    category: "Planning & Building Regs",
    subcategory: "Standard – Approvals",
    title: "Std – Approvals for identified works",
    enquiryText: "Please provide evidence of planning permission/building regulations approval (or competent person certification) for the following identified works: [WORKS]. If not available, please confirm the completion date of the works.",
    appliesTo: "purchase",
    tags: ["purchase", "planning", "building-regs", "standard"],
    whenToUse: "Only raise if specific works are identified from TA6, searches or inspection.",
    graceParagraph: "Cat B",
  },
  {
    category: "Searches",
    subcategory: "Standard – Build over",
    title: "Std – Build over agreement",
    enquiryText: "Where applicable, please confirm whether any structure has been built over a public sewer and provide any build-over agreement/approval if available.",
    appliesTo: "purchase",
    tags: ["purchase", "sewer", "build-over", "searches", "standard"],
    whenToUse: "Only raise if drainage search or plan shows a public sewer near the building.",
    graceParagraph: "Cat B",
  },
  {
    category: "Searches",
    subcategory: "Standard – Roads",
    title: "Std – Roads adoption and maintenance",
    enquiryText: "Please confirm whether roads serving the property are adopted and maintained at public expense, or provide details of maintenance arrangements.",
    appliesTo: "purchase",
    tags: ["purchase", "highways", "adoption", "searches", "standard"],
    whenToUse: "Standard search follow-up if road status is unclear.",
    graceParagraph: "Cat B",
  },
  {
    category: "Searches",
    subcategory: "Standard – Enforcement",
    title: "Std – Enforcement notices",
    enquiryText: "Please confirm whether there are any outstanding enforcement notices, stop notices, breach notices or similar affecting the property.",
    appliesTo: "purchase",
    tags: ["purchase", "enforcement", "notices", "searches", "standard"],
    whenToUse: "Standard search follow-up if planning or building regs issues indicated.",
    graceParagraph: "Cat B",
  },
  {
    category: "Searches",
    subcategory: "Standard – Environmental",
    title: "Std – Environmental notices",
    enquiryText: "Please confirm whether the seller has received any statutory notices relating to contamination or environmental remediation affecting the property.",
    appliesTo: "purchase",
    tags: ["purchase", "environmental", "contamination", "notices", "standard"],
    whenToUse: "Standard search follow-up if environmental risk flagged.",
    graceParagraph: "Cat B",
  },
  {
    category: "Completion Mechanics",
    subcategory: "Standard – Occupation",
    title: "Std – Vacant possession",
    enquiryText: "Please confirm vacant possession will be provided on completion.",
    appliesTo: "purchase",
    tags: ["purchase", "vacant-possession", "completion", "occupation", "standard"],
    whenToUse: "Standard initial enquiry on all purchase matters.",
    graceParagraph: "Cat C",
  },
  {
    category: "Completion Mechanics",
    subcategory: "Standard – Occupation",
    title: "Std – Occupiers confirmation",
    enquiryText: "Please confirm no occupiers will remain in occupation on completion.",
    appliesTo: "purchase",
    tags: ["purchase", "occupation", "standard"],
    whenToUse: "Standard initial enquiry on all purchase matters.",
    graceParagraph: "Cat C",
  },
  {
    category: "Contract & Parties",
    subcategory: "Standard – Disputes",
    title: "Std – Disputes and complaints",
    enquiryText: "Please confirm there are no ongoing disputes, complaints or notices affecting the property beyond those disclosed in the TA6.",
    appliesTo: "purchase",
    tags: ["purchase", "disputes", "notices", "standard"],
    whenToUse: "Standard initial enquiry on all purchase matters.",
    graceParagraph: "Cat C",
  },
  {
    category: "Leasehold",
    subcategory: "Standard – Term & Rent",
    title: "Std – Remaining term and rent review",
    enquiryText: "Please confirm the unexpired term and provide details of ground rent and any review provisions.",
    appliesTo: "purchase",
    tags: ["purchase", "leasehold", "ground-rent", "standard"],
    whenToUse: "Standard initial enquiry on all leasehold purchases.",
    graceParagraph: "Cat C",
  },
  {
    category: "Leasehold",
    subcategory: "Standard – Service charge",
    title: "Std – Service charge accounts / budget",
    enquiryText: "Please provide the latest service charge accounts and current budget.",
    appliesTo: "purchase",
    tags: ["purchase", "leasehold", "service-charge", "standard"],
    whenToUse: "Standard initial enquiry on all leasehold purchases.",
    graceParagraph: "Cat C",
  },
  {
    category: "Leasehold",
    subcategory: "Standard – Major works",
    title: "Std – Major works planned",
    enquiryText: "Please confirm whether any major works are planned or anticipated and provide details where available.",
    appliesTo: "purchase",
    tags: ["purchase", "leasehold", "section-20", "standard"],
    whenToUse: "Raise if there are indications of major works or large reserve fund demands.",
    graceParagraph: "Cat B",
  },
  {
    category: "Leasehold",
    subcategory: "Standard – Alienation",
    title: "Std – Alienation / licence to assign",
    enquiryText: "Please confirm any licence to assign / notice requirements and provide the landlord/managing agent's requirements and fees.",
    appliesTo: "purchase",
    tags: ["purchase", "leasehold", "licence-to-assign", "standard"],
    whenToUse: "Standard initial enquiry on all leasehold purchases.",
    graceParagraph: "Cat C",
  },
  {
    category: "Leasehold",
    subcategory: "Standard – Breach",
    title: "Std – Lease breach status",
    enquiryText: "Please confirm whether the seller is in breach of any lease covenants and whether any breach notices have been served.",
    appliesTo: "purchase",
    tags: ["purchase", "leasehold", "breach", "standard"],
    whenToUse: "Standard initial enquiry on all leasehold purchases.",
    graceParagraph: "Cat C",
  },
];

export const PURCHASE_STANDARD_TEMPLATE_TITLES = [
  "Std – Authority to sell",
  "Std – Title restrictions compliance",
  "Std – Rights of way / access sufficiency",
  "Std – Services easements",
  "Std – Discharge of registered charges",
  "Std – Vacant possession",
  "Std – Disputes and complaints",
  "Std – Roads adoption and maintenance",
  "Std – Enforcement notices",
];

export const PURCHASE_INITIAL_TEMPLATE_TITLES = [
  "Authority to act",
  "Restriction on title – consent required",
  "Discrepancy in registered proprietor name",
  "Breach of restrictive covenant – specific",
  "Positive covenant – estate maintenance",
  "Planning permission – conditions compliance",
  "Building regulations – completion certificate",
  "Extension – planning and building regs",
  "Local authority search – road adoption",
  "Drainage – connection to mains",
  "Chancel repair liability",
  "Vacant possession confirmation",
  "Key release arrangements",
  "Bank details – secure method",
  "Completion – Code for Completion by Post",
];

export const PURCHASE_TITLE_DOCS_TEMPLATE_TITLES = [
  "Authority to act",
  "Power of Attorney",
  "Personal representatives",
  "Company seller – authority",
  "Missing title deeds – unregistered land",
  "Restriction on title – consent required",
  "Notice or caution on title",
  "Discrepancy in registered proprietor name",
  "Overriding interests",
  "Adverse possession",
  "Indemnity covenant – chain of indemnity",
];

export const PURCHASE_SEARCHES_PLANNING_TEMPLATE_TITLES = [
  "Planning permission – conditions compliance",
  "Planning – enforcement notice",
  "Building regulations – completion certificate",
  "Building regulations – works without approval",
  "Listed building consent",
  "Conservation area – permitted development",
  "Local authority search – road adoption",
  "Local authority search – financial charge",
  "Environmental search – contamination flag",
  "Flood risk – insurance and history",
  "Drainage – connection to mains",
  "Public sewer within 3m",
  "Mining search – subsidence claim",
  "Replacement windows – FENSA/CERTASS",
  "Extension – planning and building regs",
];
